repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.36.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: eslint
-   repo: https://github.com/pre-commit/mirrors-jshint
    rev: 'v2.13.6'  # Use the sha / tag you want to point at
    hooks:
    -   id: jshint
