on:
  workflow_call:

jobs:
  publish_unit_tests:
    name: Publish Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Download Node Junit
        id: download_junit
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: junit
          path: test-results/junit

      - name: Download Inspec Junit
        id: download_inspec
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: inspec
          path: test-results/inspec

      - name: Download Coverage
        id: download_coverage
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: coverage
          path: coverage

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2.23.0
        if: always()
        with:
          check_name: "Unit Test Results"
          files: |
            test-results/junit/*.xml
            test-results/inspec/*.xml

      - name: Coverage Report
        uses: lucassabreu/comment-coverage-clover@main
        with:
          file: "/home/runner/work/opg-pdf-service/opg-pdf-service/coverage/clover.xml"
          min-line-coverage: 89
          min-method-coverage: 90
